apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  labels:
    name: flaskapp
spec:
  selector:
    app: flaskapp
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: gajdulj/flaskapp:capstone
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
              name: http-server