version: 2.1

# commands:
#   here put reusable commands

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: python:3.7.3-stretch

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            pwd
            ls
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install

      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      - run:
          name: get sudo
          command: apt-get update && apt-get -y install sudo

      - run:
          name: Install Docker via apk
          command: |
            # setup repository
            sudo apt-get update
            
            sudo apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
            
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" -y
            # install docker engine
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - run:
          name: run docker locally
          command: |
            . venv/bin/activate
            docker build -t flaskapp:capstone .

            # List docker images
            docker image ls

            # Run flask app
            docker run -p 8000:80 flaskapp:capstone
      - run:
          name: Upload docker image
          command: |
            dockerpath="gajdulj/flaskapp"
            # Authenticate & tag
            echo "Docker ID and Image: $dockerpath"
            echo "1 complete"
            docker login -u "gajdulj" -p "$dockerhubpass"
            echo "2 complete"
            docker flaskapp:capstone gajdulj/flaskapp:capstone
            echo "3 complete"
            # Push image to a docker repository
            docker push gajdulj/flaskapp:capstone
            echo "end"
workflows:
  default:
    jobs:
      - build